// Importing express
import express from 'express'
// importing url validation 
import {shortenPostRequestBodySchema} from '../validation/request.validation.js'
// Importing db to insert url
import {db} from '../db/index.js'
// inserting models (url table)
import {urlsTable} from '../models/index.js'
// Importing nanoid 
import {nanoid} from 'nanoid'

// creating router from express
const router = express.Router()

// Creating new post route
router.post('/shorten', async function (req, res) {
    // Making sure user is authenticated
    const userID = req.user.id

    // Returning response if user id does not exists
    if (!userID) return res.status(401).json({error: `You must be logged in to access this resource`})

    // Validating result
    const validationResult = await shortenPostRequestBodySchema.safeParseAsync(req.body)

    // Checking and giving an returning if any error occurs
    if (validationResult.error) {
        return res.status(400).json({error: validationResult.error.message})
    }
    
    // Getting and storing url from url variable
    const {url, code} = validationResult.data

    // Inserting the code in table if provided else generated by nanoid of 6 chars
    const shortCode = code ?? nanoid(6);

    // Inserting url and code (if given) and storing it in result
    const [result] = await db.insert(urlsTable).values({
        // Getting short code
        shortCode,
        // targetUrl
        targetURL: url,
        // user id
        userId: req.user.id
    }).returning({
        id: urlsTable.id,
        shortCode: urlsTable.shortCode,
        targetURL: urlsTable.targetURL
    })
})


// Exporting router
export default router