// Importing express
import express from 'express'
// importing url validation 
import {shortenPostRequestBodySchema} from '../validation/request.validation.js'
// Importing db to insert url
import {db} from '../db/index.js'
// inserting models (url table)
import {urlsTable} from '../models/index.js'
// Importing nanoid 
import {nanoid} from 'nanoid'
// importing enusure authenticated middelware
import {ensureAuthenticated} from '../middleware/auth.middleware.js'
// Importing url insertion method from url service file
import {newUrlInsert} from '../services/url.service.js'


// creating router from express
const router = express.Router()

// Creating new post route
router.post('/shorten', ensureAuthenticated ,async function (req, res) {
    // Validating result
    const validationResult = await shortenPostRequestBodySchema.safeParseAsync(req.body)

    // Checking and giving an returning if any error occurs
    if (validationResult.error) {
        return res.status(400).json({error: validationResult.error.format()})
    }
    
    // Getting and storing url from url variable
    const {url, code} = validationResult.data

    // Inserting the code in table if provided else generated by nanoid of 6 chars
    const shortCode = code ?? nanoid(6);

    // Getting userId
    const userId = req.user.id

    // Storing result from our method newUrlInsert
    const result = await newUrlInsert(shortCode, url, userId)

    // Returning result
    return res.status(201).json(result)
})


// Exporting router
export default router