// Importing express
import express from 'express'
// importing url validation 
import {shortenPostRequestBodySchema} from '../validation/request.validation.js'
// Importing db to insert url
import {db} from '../db/index.js'
// inserting models (url table)
import {urlsTable} from '../models/index.js'
// Importing nanoid 
import {nanoid} from 'nanoid'
// importing enusure authenticated middelware
import {ensureAuthenticated} from '../middleware/auth.middleware.js'
// Importing url insertion method from url service file
import {newUrlInsert} from '../services/url.service.js'
// Importing eq and and
import { and, eq } from 'drizzle-orm'

// creating router from express
const router = express.Router()

// Creating POST route for shortening url
router.post('/shorten', ensureAuthenticated ,async function (req, res) {
    // Validating result
    const validationResult = await shortenPostRequestBodySchema.safeParseAsync(req.body)

    // Checking and giving an returning if any error occurs
    if (validationResult.error) {
        return res.status(400).json({error: validationResult.error.format()})
    }
    
    // Getting and storing url from url variable
    const {url, code} = validationResult.data

    // Inserting the code in table if provided else generated by nanoid of 6 chars
    const shortCode = code ?? nanoid(6);

    // Getting userId
    const userId = req.user.id

    // Storing result from our method newUrlInsert
    const result = await newUrlInsert(shortCode, url, userId)

    // Returning result
    return res.status(201).json(result)
})

// Creating a GET route to fetch all shortened urls of current user
router.get('/codes', ensureAuthenticated, async function (req, res) {
    // Getting all codes 
    const codes = await db
        .select()
        .from(urlsTable)
        .where(eq(urlsTable.userId, req.user.id))
    
    // Return all codes in JSON
    return res.status(200).json({ codes })
})

// Creating a DELETE route to delete short code by code id
router.delete('/:id', ensureAuthenticated, async function (req, res) {
    // Getting id from url parameter
    const id = req.params.id

    // Deleting only user assigned codes
    await db.delete(urlsTable)
        .where(and(eq(urlsTable.id, id), eq(urlsTable.userId, req.user.id)))

    return res.status(200).json({deleted: true})
})

// Creating GET route for short code to original url
router.get('/:shortCode', async function (req, res) {
    // Getting short code from req parameters
    const code = req.params.shortCode

    // getting URL based in short code
    const [result] = await db.select({
        targetURL: urlsTable.targetURL
    })
    .from(urlsTable)
    .where(eq(urlsTable.shortCode, code))

    // If no url found
    if (!result) {
        return res.status(404).json({error: 'Invalid URL'})
    }

    // Redirecting to target URL
    return res.redirect(result.targetURL)
})

// Exporting router
export default router